const {readFileSync}=require('node:fs');
const assert=require('node:assert/strict');
const ts=require('typescript');
const vm=require('node:vm');
function load(path,extra={}){const exports={};vm.runInNewContext(ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,...extra});return exports;}
const {mergeDryingItems,applyCatalogPrice}=load('lib/document-items.ts');
const suggestion={description:'Technische Trocknung – Gerät (Raum) [TEST]',quantity:2.75,unit:'Tage',source_type:'drying:test'};
const first=mergeDryingItems([], [suggestion]);
assert.equal(first.length,1);assert.equal(first[0].quantity,2.75);
assert.equal(mergeDryingItems(first,[suggestion]).length,1);
first[0].unit_price=14;
const updated=mergeDryingItems(first,[{...suggestion,quantity:5}],true);
assert.equal(updated[0].unit_price,14);assert.equal(updated[0].quantity,5);assert.equal(first[0].quantity,2.75);
const legacy={...first[0],description:'Technische Trocknung – Gerät (Raum)',source_type:'drying'};
assert.equal(mergeDryingItems([legacy],[suggestion],true).length,1);
const manual={...first[0],description:'Vorbereitung Trocknung',source_type:'manual'};
assert.equal(mergeDryingItems([manual],[suggestion],true).length,2);
assert.equal(mergeDryingItems(first,[{...suggestion,quantity:0}],true)[0].quantity,0);
assert.equal(mergeDryingItems([{...first[0],unit:'Pauschale',quantity:1}],[{...suggestion,quantity:15}],true)[0].quantity,1);
const two=mergeDryingItems(first,[{...suggestion,source_type:'drying:second'}]);
assert.equal(two.length,2);
assert.equal(applyCatalogPrice(first[0],{unit:'Tag',unit_price:25}).quantity,2.75);
assert.equal(applyCatalogPrice(first[0],{unit:'Tag',unit_price:25}).description,first[0].description);
assert.throws(()=>applyCatalogPrice(first[0],{unit:'Pauschale',unit_price:500}),/Einheiten/);
assert.throws(()=>applyCatalogPrice(first[0],{unit:'Tage',unit_price:null}),/keinen/);
const source=readFileSync('app/api/articles/route.ts','utf8');
const search=vm.runInNewContext(ts.transpileModule(source.slice(source.indexOf('function norm'),source.indexOf('export async function GET'))+';({score})',{compilerOptions:{target:ts.ScriptTarget.ES2020}}).outputText);
const article={article_number:'100',name:'Technische Trocknung',description:'Gerätemiete',source:''};
assert.ok(search.score(article,'Trockner')>0);assert.ok(search.score(article,'100')>search.score(article,'Trockner'));
assert.equal(search.score(article,'Fliesen'),0);
console.log('Dokumentpositionen, Doppelklickschutz, Laufzeiten, Bestandspreise, Altdaten, Einheiten und Artikelsuche: bestanden.');
