"use client";
import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Entity="time"|"schedule"|"finance"|"reserves"|"family"|"mail"|"documents";
type Field={name:string;label:string;type?:string;options?:[string,string][];wide?:boolean;required?:boolean};
const tabs:[Entity|string,string][]=[["today","Heute"],["time","Zeiten"],["schedule","Planung"],["finance","Finanzen"],["reserves","Rücklagen"],["family","Familie"],["mail","E-Mail & Kalender"],["documents","Dokumente"]];
const fields:Record<Entity,Field[]>={
 time:[{name:"area",label:"Bereich",type:"select",options:[["erhard","Erhard IT/Dienstleistung"],["dryland","Dryland/Trocknung"],["ecg","ECG Hausmeister"],["zeiss","Zeiss"],["family","Familie"]]},{name:"activity",label:"Tätigkeit",required:true},{name:"customer",label:"Kunde"},{name:"location",label:"Ort"},{name:"started_at",label:"Beginn",type:"datetime-local",required:true},{name:"ended_at",label:"Ende",type:"datetime-local"},{name:"travel_minutes",label:"Fahrtzeit (Min.)",type:"number"},{name:"notes",label:"Notiz",type:"textarea",wide:true},{name:"billable",label:"Abrechenbar",type:"checkbox"},{name:"volunteer",label:"Freiwilliger Dienst",type:"checkbox"},{name:"sunday",label:"Sonntag",type:"checkbox"}],
 schedule:[{name:"category",label:"Kategorie",type:"select",options:[["shift","Zeiss-Schicht"],["family","Familienzeit"],["ecg","ECG"],["appointment","Termin"],["business","Geschäftlich"]]},{name:"title",label:"Titel",required:true},{name:"starts_at",label:"Beginn",type:"datetime-local",required:true},{name:"ends_at",label:"Ende",type:"datetime-local"},{name:"location",label:"Ort"},{name:"notes",label:"Notiz",type:"textarea",wide:true},{name:"protected",label:"Geschützte Familien-/Ruhezeit",type:"checkbox",wide:true}],
 finance:[{name:"entry_date",label:"Datum",type:"date",required:true},{name:"kind",label:"Art",type:"select",options:[["income","Einnahme"],["expense","Ausgabe"]]},{name:"scope",label:"Bereich",type:"select",options:[["private","Privat/Familie"],["erhard","Erhard"],["dryland","Dryland"],["ecg","ECG"]]},{name:"category",label:"Kategorie",required:true},{name:"description",label:"Beschreibung",required:true},{name:"amount",label:"Betrag (€)",type:"number",required:true},{name:"recurring",label:"Wiederkehrend",type:"checkbox"},{name:"interval_months",label:"Rhythmus (Monate)",type:"number"},{name:"notes",label:"Notiz",type:"textarea",wide:true}],
 reserves:[{name:"name",label:"Rücklage",required:true},{name:"scope",label:"Bereich",type:"select",options:[["private","Privat/Familie"],["erhard","Erhard"],["dryland","Dryland"]]},{name:"target_amount",label:"Benötigter Betrag (€)",type:"number",required:true},{name:"saved_amount",label:"Bereits zurückgelegt (€)",type:"number"},{name:"due_date",label:"Zahlungstermin",type:"date"},{name:"interval_months",label:"Zahlungsrhythmus (Monate)",type:"number"},{name:"notes",label:"Notiz",type:"textarea",wide:true}],
 family:[{name:"name",label:"Name",required:true},{name:"member_role",label:"Rolle",type:"select",options:[["spouse","Ehepartnerin"],["child","Kind"],["other","Weitere Person"]]},{name:"monthly_allowance",label:"Taschengeld/Monat (€)",type:"number"},{name:"access_level",label:"Spätere Berechtigung",type:"select",options:[["family","Familienverwaltung"],["own","Nur eigene Daten"],["none","Kein Zugang"]]},{name:"notes",label:"Notiz",type:"textarea",wide:true}],
 mail:[{name:"label",label:"Bezeichnung",required:true},{name:"email",label:"E-Mail-Adresse",type:"email",required:true},{name:"provider",label:"Anbieter",type:"select",options:[["gmail","Gmail"],["outlook","Microsoft/Outlook"],["all-inkl","All-Inkl"],["strato","Strato"],["gmx","GMX"],["other","Anderer Anbieter"]]},{name:"connection_type",label:"Verbindung",type:"select",options:[["imap","IMAP / App-Passwort"],["oauth","OAuth (Vorbereitung)"]]},{name:"host",label:"IMAP-Server"},{name:"port",label:"Port",type:"number"},{name:"security",label:"Sicherheit",type:"select",options:[["tls","SSL/TLS"],["starttls","STARTTLS"]]},{name:"secret",label:"App-Passwort (verschlüsselt)",type:"password"},{name:"notes",label:"Notiz",type:"textarea",wide:true}],
 documents:[{name:"document_type",label:"Dokumentart",type:"select",options:[["insurance","Versicherung"],["invoice","Rechnung"],["vehicle","Fahrzeug"],["contract","Vertrag"],["other","Sonstiges"]]},{name:"title",label:"Titel",required:true},{name:"issuer",label:"Aussteller"},{name:"policy_number",label:"Police-/Vertragsnummer"},{name:"amount",label:"Betrag (€)",type:"number"},{name:"due_date",label:"Fälligkeit",type:"date"},{name:"interval_months",label:"Rhythmus (Monate)",type:"number"}]
};
const defaults:Record<Entity,any>={time:{area:"erhard",activity:"",started_at:localNow(),ended_at:"",travel_minutes:0,billable:true,volunteer:false,sunday:new Date().getDay()===0},schedule:{category:"appointment",title:"",starts_at:localNow(),ends_at:"",protected:false},finance:{entry_date:new Date().toISOString().slice(0,10),kind:"expense",scope:"private",category:"",description:"",amount:"",recurring:false},reserves:{name:"",scope:"private",target_amount:"",saved_amount:0,interval_months:12},family:{name:"",member_role:"child",monthly_allowance:0,access_level:"own"},mail:{label:"",email:"",provider:"gmail",connection_type:"oauth",security:"tls",port:993},documents:{document_type:"insurance",title:"",amount:""}};
function localNow(){const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
function inputDate(v:any){if(!v)return "";const d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function euro(c:any){return new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(c||0)/100)}
function duration(m:any){const n=Math.round(Number(m||0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")} h`}

export default function OrganizationHub({displayName}:{displayName:string}){
 const[tab,setTab]=useState<string>("today"),[items,setItems]=useState<any[]>([]),[summary,setSummary]=useState<any>(null),[form,setForm]=useState<any>(defaults.time),[editing,setEditing]=useState<string|null>(null),[trash,setTrash]=useState(false),[status,setStatus]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[documentImage,setDocumentImage]=useState("");
 const entity=(tab==="today"?"time":tab) as Entity;
 async function load(next=entity){setBusy(true);setError("");try{const[r,s]=await Promise.all([fetch(`/api/organization/data?entity=${next}&trash=${trash?1:0}`,{cache:"no-store"}),fetch("/api/organization/summary",{cache:"no-store"})]);if(!r.ok)throw new Error((await r.json()).error);setItems(await r.json());if(s.ok)setSummary(await s.json())}catch(e){setError(e instanceof Error?e.message:"Fehler beim Laden") }finally{setBusy(false)}}
 useEffect(()=>{if(tab!=="today")load(entity);else fetch("/api/organization/summary",{cache:"no-store"}).then(r=>r.json()).then(setSummary).catch(()=>{})},[tab,trash]);
 function choose(next:string){setTab(next);setEditing(null);setForm(defaults[(next==="today"?"time":next) as Entity]);setStatus("");setError("")}
 function change(name:string,value:any){setForm((f:any)=>({...f,[name]:value}))}
 function edit(item:any){const copy={...item};for(const key of ["started_at","ended_at","starts_at","ends_at"])if(copy[key])copy[key]=inputDate(copy[key]);if(item.amount_cents!=null)copy.amount=Number(item.amount_cents)/100;if(item.target_cents!=null)copy.target_amount=Number(item.target_cents)/100;if(item.saved_cents!=null)copy.saved_amount=Number(item.saved_cents)/100;if(item.monthly_allowance_cents!=null)copy.monthly_allowance=Number(item.monthly_allowance_cents)/100;setForm(copy);setEditing(item.id);window.scrollTo({top:230,behavior:"smooth"})}
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/organization/data",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity,id:editing,data:form})});const j=await r.json();if(!r.ok)throw new Error(j.error);setStatus(editing?"Änderung gespeichert.":"Eintrag gespeichert.");setEditing(null);setForm({...defaults[entity]});await load(entity)}catch(e){setError(e instanceof Error?e.message:"Speichern fehlgeschlagen") }finally{setBusy(false)}}
 async function remove(id:string,restore=false){if(!restore&&!confirm("Eintrag in den Papierkorb verschieben?"))return;const r=await fetch("/api/organization/data",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity,id,restore})});if(r.ok){setStatus(restore?"Eintrag wiederhergestellt.":"Eintrag liegt im Papierkorb.");load(entity)}else setError((await r.json()).error)}
 async function analyze(file:File){setBusy(true);setError("");try{const image=await resize(file);setDocumentImage(image);const r=await fetch("/api/organization/analyze-document",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image})});const j=await r.json();if(!r.ok)throw new Error(j.error);setForm({...defaults.documents,...j.result});setStatus("KI-Vorschlag übernommen. Bitte prüfen und erst dann speichern.")}catch(e){setError(e instanceof Error?e.message:"Analyse fehlgeschlagen")}finally{setBusy(false)}}
 async function syncMail(id:string){setBusy(true);setError("");try{const r=await fetch("/api/organization/mail-sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})}),j=await r.json();if(!r.ok)throw new Error(j.error);setStatus(j.message);await load("mail")}catch(e){setError(e instanceof Error?e.message:"Abruf fehlgeschlagen")}finally{setBusy(false)}}
 const visible=useMemo(()=>items.filter(x=>trash||!x.deleted_at),[items,trash]);
 return <>
  <header className="orgHero"><div className="orgHead"><div className="orgBrand"><img src="/organization-logo.png" alt="Erhard Organisationszentrale"/><div><span className="pill">Persönlicher Admin-Bereich</span><h1>Organisationszentrale</h1><p>Hallo {displayName}. Arbeit, Familie, Finanzen und Termine an einem geschützten Ort.</p></div></div><div className="actions"><Link className="button secondary" href="/">Schadenmanagement</Link><button className="button secondary" onClick={()=>load(entity)}>Aktualisieren</button></div></div></header>
  <nav className="orgTabs">{tabs.map(([key,label])=><button key={key} className={`orgTab ${tab===key?"active":""}`} onClick={()=>choose(key)}>{label}</button>)}</nav>
  {error&&<div className="orgStatus error">{error}</div>}{status&&<div className="orgStatus">{status}</div>}
  {tab==="today"?<Today summary={summary} refresh={()=>fetch("/api/organization/summary",{cache:"no-store"}).then(r=>r.json()).then(setSummary)}/>:<>
   {tab==="schedule"&&<ShiftInfo/>}{tab==="mail"&&<MailInfo/>}
   <div className="orgSplit"><section className="orgPanel"><h2>{editing?"Eintrag bearbeiten":"Neu anlegen"}</h2>
    {tab==="documents"&&<div className="orgFile"><label>Foto aufnehmen oder Datei wählen<input type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&analyze(e.target.files[0])}/></label>{documentImage&&<div className="small muted">Bild analysiert – Original wird in dieser Ausbaustufe nicht dauerhaft gespeichert.</div>}</div>}
    <form className="orgForm" onSubmit={save}>{fields[entity].map(f=><FieldInput key={f.name} field={f} value={form[f.name]} change={change}/>)}<div className="wide actions"><button className="button" disabled={busy}>{busy?"Bitte warten …":editing?"Änderung speichern":"Speichern"}</button>{editing&&<button type="button" className="button secondary" onClick={()=>{setEditing(null);setForm({...defaults[entity]})}}>Abbrechen</button>}</div></form>
   </section><section className="orgPanel"><div className="sectionHeader"><div><h2>Einträge</h2><span className="small muted">{visible.length} Datensätze</span></div><label className="orgCheck"><input type="checkbox" checked={trash} onChange={e=>setTrash(e.target.checked)}/>Papierkorb anzeigen</label></div>{busy&&!items.length?<div className="empty">Lade Daten …</div>:<EntityTable entity={entity} items={visible} edit={edit} remove={remove} syncMail={syncMail}/>}</section></div>
  </>}
 </>
}

function FieldInput({field,value,change}:{field:Field;value:any;change:(n:string,v:any)=>void}){const cls=field.wide?"wide":"";if(field.type==="checkbox")return <label className={`orgCheck ${cls}`}><input type="checkbox" checked={!!value} onChange={e=>change(field.name,e.target.checked)}/>{field.label}</label>;return <label className={`field ${cls}`}><span>{field.label}</span>{field.type==="select"?<select value={value??""} onChange={e=>change(field.name,e.target.value)}>{field.options?.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:field.type==="textarea"?<textarea value={value??""} onChange={e=>change(field.name,e.target.value)}/>:<input type={field.type||"text"} step={field.type==="number"?"0.01":undefined} required={field.required} value={value??""} onChange={e=>change(field.name,e.target.value)}/>}</label>}
function Today({summary:s,refresh}:{summary:any;refresh:()=>void}){if(!s)return <div className="orgPanel empty">Übersicht wird geladen …</div>;return <><div className="orgKpis"><Kpi label="Erfasste Zeit diese Woche" value={duration(s.week_minutes)}/><Kpi label="ECG angerechnet" value={duration(s.ecg_week_minutes+s.ecg_presence_credit_minutes)}/><Kpi label="ECG noch offen" value={duration(s.ecg_remaining_minutes)}/><Kpi label="Freiwilliger Dienst" value={duration(s.volunteer_minutes)}/><Kpi label="Monatlicher Überschuss" value={euro(s.income_cents-s.expense_cents)}/><Kpi label="Rücklagen pro Monat" value={euro(s.reserve_monthly_cents)}/></div><div className="orgSplit"><section className="orgPanel"><h2>Nächste Termine</h2>{s.next?.length?s.next.map((x:any)=><div className="card" key={x.id}><strong>{x.title}</strong><div className="small muted">{new Date(x.starts_at).toLocaleString("de-DE")}{x.location?` · ${x.location}`:""}</div></div>):<div className="empty">Noch keine Termine hinterlegt.</div>}<div className="divider"/><h3>Wichtige E-Mails</h3>{s.mail?.length?s.mail.map((x:any,i:number)=><div className="card" key={i}><strong>{x.subject}</strong><div className="small muted">{x.sender} · {x.suggested_action}</div></div>):<div className="small muted">Keine wichtigen ungelesenen E-Mails vorgemerkt.</div>}</section><section className="orgPanel"><h2>Dein Wochenrahmen</h2><div className="orgInfo">ECG-Ziel: {duration(s.ecg_target_minutes)}. Davon sind aktuell {duration(s.ecg_presence_credit_minutes)} Präsenz/Rufbereitschaft als konfigurierbarer Ausgleich berücksichtigt. Freiwillige Dienste werden separat ausgewiesen und verändern das Minijob-Soll nicht.</div><EcgSettings summary={s} refresh={refresh}/><div className="divider"/><p><strong>Familie und Erholung zuerst sichtbar machen:</strong> Trage feste Familienzeiten als „geschützt“ ein. So erkennt die Planung Konflikte, statt freie Kalenderflächen automatisch als verfügbare Arbeitszeit zu behandeln.</p></section></div></>}
function EcgSettings({summary,refresh}:{summary:any;refresh:()=>void}){const[target,setTarget]=useState(summary.ecg_target_minutes/60),[credit,setCredit]=useState(summary.ecg_presence_credit_minutes/60),[message,setMessage]=useState("");async function save(){const r=await fetch("/api/organization/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ecg_weekly_target_minutes:Number(target)*60,ecg_presence_credit_minutes:Number(credit)*60,commute_km:32,commute_minutes:25})}),j=await r.json();setMessage(r.ok?"Wochenrahmen gespeichert.":j.error);if(r.ok)refresh()}return <div className="orgForm" style={{marginTop:14}}><label className="field"><span>ECG-Soll (Std./Woche)</span><input type="number" step="0.25" value={target} onChange={e=>setTarget(e.target.valueAsNumber)}/></label><label className="field"><span>Präsenz-Ausgleich (Std.)</span><input type="number" step="0.25" value={credit} onChange={e=>setCredit(e.target.valueAsNumber)}/></label><div className="wide actions"><button className="button secondary" onClick={save}>Rahmen speichern</button>{message&&<span className="small muted">{message}</span>}</div></div>}
function Kpi({label,value}:{label:string;value:string}){return <div className="orgKpi"><span className="small muted">{label}</span><strong>{value}</strong></div>}
function ShiftInfo(){return <div className="orgPanel"><h2>Hinterlegte Zeiss-Schichtregeln</h2><div className="orgInfo"><strong>Bis 03.11.2026:</strong> Wochenendmodell – Früh 05:30–15:00, Spät ca. 13:30–23:30, Nacht 21:30–06:30; jeweils mit deinem ±30-Minuten-Rahmen.<br/><strong>Ab 04.11.2026:</strong> Früh 04:30–13:05, Spät 12:50–22:20 (freitags flexibel ab 18:00), Nacht 21:30–05:40; sonntags flexibler Start 20:00–24:00. Pendelweg Hussenhofen–Oberkochen: 32 km, Richtwert 25 Minuten je Strecke.</div></div>}
function MailInfo(){return <div className="orgPanel"><h2>Konten verbinden</h2><div className="orgDangerNote">All-Inkl, Strato, GMX sowie Gmail/Microsoft mit aktiviertem App-Passwort können per IMAP verbunden werden. Das App-Passwort wird serverseitig mit AES-256 verschlüsselt und niemals wieder angezeigt. Für die komfortable OAuth-Anmeldung bei Gmail und Microsoft müssen nach dem ersten Deployment noch eigene App-Zugangsdaten hinterlegt werden. Das Entfernen eines Kontos löscht nur die Verknüpfung, niemals E-Mails beim Anbieter.</div></div>}
function EntityTable({entity,items,edit,remove,syncMail}:{entity:Entity;items:any[];edit:(x:any)=>void;remove:(id:string,r?:boolean)=>void;syncMail:(id:string)=>void}){if(!items.length)return <div className="empty">Noch keine Einträge.</div>;return <div className="orgTableWrap"><table className="orgTable"><thead><tr><th>Bezeichnung</th><th>Details</th><th>Wert/Zeit</th><th>Aktionen</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className={x.deleted_at?"orgRowDeleted":""}><td><strong>{x.activity||x.title||x.description||x.name||x.label}</strong><br/><span className="small muted">{x.customer||x.issuer||x.email||x.category||x.scope}</span></td><td>{details(entity,x)}</td><td>{value(entity,x)}</td><td><div className="orgRowActions">{entity==="mail"&&!x.deleted_at&&<button className="orgMiniButton" onClick={()=>syncMail(x.id)}>Abrufen</button>}{!x.deleted_at&&<button className="orgMiniButton" onClick={()=>edit(x)}>Bearbeiten</button>}<button className={`orgMiniButton ${x.deleted_at?"":"danger"}`} onClick={()=>remove(x.id,!!x.deleted_at)}>{x.deleted_at?"Wiederherstellen":"Löschen"}</button></div></td></tr>)}</tbody></table></div>}
function details(e:Entity,x:any){if(e==="time")return <>{new Date(x.started_at).toLocaleString("de-DE")}<br/><span className="small muted">{x.area}{x.volunteer?" · freiwillig":""}{x.travel_minutes?` · Fahrt ${x.travel_minutes} Min.`:""}</span></>;if(e==="schedule")return <>{new Date(x.starts_at).toLocaleString("de-DE")}<br/><span className="small muted">{x.location}{x.protected?" · geschützt":""}</span></>;if(e==="finance")return <>{new Date(x.entry_date).toLocaleDateString("de-DE")} · {x.scope}</>;if(e==="reserves")return <>Fällig: {x.due_date?new Date(x.due_date).toLocaleDateString("de-DE"):"laufend"}<br/><span className="small muted">Gespart {euro(x.saved_cents)}</span></>;if(e==="family")return <>{x.member_role} · Zugriff: {x.access_level}</>;if(e==="mail")return <>{x.provider} · {x.connection_type}<br/><span className="small muted">{x.status}</span></>;return <>{x.document_type}<br/><span className="small muted">{x.policy_number}</span></>}
function value(e:Entity,x:any){if(e==="time")return duration(x.duration_minutes);if(e==="finance")return <span className={x.kind==="income"?"orgMoneyPos":"orgMoneyNeg"}>{x.kind==="income"?"+":"−"}{euro(x.amount_cents)}</span>;if(e==="reserves")return <>{euro(x.monthly_required_cents)} / Monat</>;if(e==="family")return euro(x.monthly_allowance_cents);if(e==="documents")return x.amount_cents==null?"–":euro(x.amount_cents);return ""}
function resize(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error("Datei konnte nicht gelesen werden."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("Bildformat wird nicht unterstützt."));img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.82))};img.src=String(reader.result)};reader.readAsDataURL(file)})}
