"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {SelectOrCustom,STANDARD_FLOORS,STANDARD_ROOMS} from "@/components/RoomFields";
import DamageReportEditor from "@/components/DamageReportEditor";
import DeleteCaseButton from "@/components/DeleteCaseButton";
import AssignmentEditor from "@/components/AssignmentEditor";

type CaseData={id:string;title:string;case_number:string|null;status:string;company_id:string;company_name:string;company_code:string;customer_name:string|null;object_street:string|null;object_postal_code:string|null;object_city:string|null;floor:string|null;unit:string|null;insurer:string|null;insurance_number:string|null;claim_number:string|null;damage_cause:string|null;damage_description:string|null;recommended_action:string|null};
type Energy={id:string;unit_name:string|null;start_date:string|null;end_date:string|null;consumption_kwh:number|null;price_per_kwh:number|null};
type Measurement={id:string;room:string|null;floor:string|null;component:string|null;device:string|null;value_numeric:number|null;unit:string|null;assessment:string|null;notes:string|null};
type Photo={id:string;category:string;room:string|null;component:string|null;caption:string|null;file_url:string};
type Eq={id:string;company_id:string;equipment_code:string;name:string;equipment_type:string|null;serial_number:string|null;power_watts:number|null};
type Drying={id:string;room:string|null;installed_at:string;removed_at:string|null;drying_method:string|null;notes:string|null;equipment_code:string|null;equipment_name:string|null};
type WorkReport={id:string;report_date:string;worker_name:string|null;work_start:string|null;work_end:string|null;trips_count:number;description:string|null};

export default function CaseDetail({id}:{id:string}){
 const[data,setData]=useState<CaseData|null>(null),[energy,setEnergy]=useState<Energy[]>([]),[measurements,setMeasurements]=useState<Measurement[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[drying,setDrying]=useState<Drying[]>([]),[reports,setReports]=useState<WorkReport[]>([]),[equipment,setEquipment]=useState<Eq[]>([]);
 const[tab,setTab]=useState("overview"),[error,setError]=useState(""),[message,setMessage]=useState(""),[dryingCategory,setDryingCategory]=useState("technical"),[aiPhoto,setAiPhoto]=useState(false),[userRole,setUserRole]=useState("");

 async function load(){try{setError("");const urls=[`/api/cases/${id}`,`/api/cases/${id}/energy`,`/api/cases/${id}/measurements`,`/api/cases/${id}/photos`,`/api/cases/${id}/drying`,`/api/cases/${id}/work-reports`];const r=await Promise.all(urls.map(u=>fetch(u,{cache:"no-store"})));if(!r[0].ok)throw new Error("Schaden konnte nicht geladen werden.");const d=await r[0].json();setData(d);if(r[1].ok)setEnergy(await r[1].json());if(r[2].ok)setMeasurements(await r[2].json());if(r[3].ok)setPhotos(await r[3].json());if(r[4].ok)setDrying(await r[4].json());if(r[5].ok)setReports(await r[5].json());const eq=await fetch(`/api/equipment?company_id=${d.company_id}`,{cache:"no-store"});if(eq.ok)setEquipment(await eq.json())}catch(e){setError(e instanceof Error?e.message:"Fehler")}}
 useEffect(()=>{load();fetch("/api/auth/status",{cache:"no-store"}).then(r=>r.json()).then(j=>setUserRole(j?.user?.role||"")).catch(()=>{})},[id]);

 async function post(path:string,form:HTMLFormElement,transform?:(o:any)=>Promise<any>|any){setError("");setMessage("");try{let body:any=Object.fromEntries(new FormData(form).entries());if(transform)body=await transform(body);const res=await fetch(`/api/cases/${id}/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await res.json();if(!res.ok)throw new Error(j.error||"Speichern fehlgeschlagen.");form.reset();setMessage("Gespeichert.");await load()}catch(e){setError(e instanceof Error?e.message:"Fehler")}}
 async function photoTransform(o:any){const input=document.querySelector<HTMLInputElement>("#photoFile"),file=input?.files?.[0];if(!file)throw new Error("Bitte ein Foto auswählen.");return {...o,file_url:await compressImage(file,1280,.72)}}
 async function describePhoto(){setError("");setMessage("");const form=document.querySelector<HTMLFormElement>("#photoForm"),input=document.querySelector<HTMLInputElement>("#photoFile"),file=input?.files?.[0];if(!form||!file){setError("Bitte zuerst ein Foto aufnehmen oder auswählen.");return}setAiPhoto(true);try{const image=await compressImage(file,1400,.76);const context=`Schadensfall: ${data?.title||""}. Schadensursache: ${data?.damage_cause||"nicht angegeben"}.`;const r=await fetch("/api/ai/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"photo_description",image,context})});const j=await r.json();if(!r.ok)throw new Error(j.error||"KI nicht verfügbar.");const d=j.result||{};const set=(n:string,v:any)=>{const el=form.elements.namedItem(n) as HTMLInputElement|HTMLTextAreaElement|null;if(el&&v)el.value=String(v)};set("caption",d.description||d.damage_observation);set("room",d.room);set("component",d.component);setMessage("KI-Beschreibung eingetragen. Bitte fachlich prüfen und dann Foto speichern.")}catch(e){setError(e instanceof Error?e.message:"KI-Analyse fehlgeschlagen.")}finally{setAiPhoto(false)}}

 const filteredEquipment=useMemo(()=>equipment.filter(e=>e.equipment_type===dryingCategory||e.equipment_type==="universal"),[equipment,dryingCategory]);
 if(error&&!data)return <div className="error">{error}</div>;if(!data)return <div className="card empty">Lade Schadenakte …</div>;
 const address=[data.object_street,[data.object_postal_code,data.object_city].filter(Boolean).join(" ")].filter(Boolean).join(", ");
 const tabs=[["overview","Übersicht"],["damage","Schadensaufnahme"],["photos","Fotos"],["measurements","Messungen"],["drying","Trocknung"],["reports","Rapporte"],["energy","Energie"],["documents","Dokumente"]];

 return <><section className="hero"><span className="pill">{data.company_code}</span><h1>{data.title}</h1><p className="muted">{data.company_name}{data.case_number?` · ${data.case_number}`:""}<br/>{address||"Objektadresse noch offen"}</p><div className="actions noPrint" style={{marginTop:12}}><Link className="button" href={`/cases/${id}/report`}>Schadensbericht öffnen</Link>{(userRole==="admin"||userRole==="buero")&&<Link className="button secondary" href={`/documents/new?case_id=${id}`}>Angebot / Rechnung erstellen</Link>}{userRole==="admin"&&<Link className="button secondary" href="/equipment">Geräte verwalten</Link>}{userRole==="admin"&&<DeleteCaseButton id={id}/>}</div></section>
 <div className="tabs">{tabs.map(([k,l])=><button key={k} className="tab" onClick={()=>setTab(k)}>{l}</button>)}</div>{message&&<div className="notice section">{message}</div>}{error&&<div className="error section">{error}</div>}

 {tab==="overview"&&<>
 <section className="section grid cols3"><div className="card"><div className="stat">{data.status}</div><div className="kpiLabel">Status</div></div><div className="card"><div className="stat">{photos.length}</div><div className="kpiLabel">Fotos</div></div><div className="card"><div className="stat">{measurements.length}</div><div className="kpiLabel">Messungen</div></div><div className="card"><h3>Auftraggeber</h3>{data.customer_name||"–"}</div><div className="card"><h3>Versicherung</h3>{data.insurer||"–"}<div className="muted small">{data.claim_number||""}</div></div><div className="card"><h3>Trocknung</h3>{drying.length} Geräte-/Trocknungseinträge</div></section>
 <section className="section dangerZone">
   <div>
     <h3>Schadensfall löschen</h3>
     <p>Nur verwenden, wenn dieser Schadensfall nicht mehr benötigt wird. Zugehörige Messungen, Fotos, Rapporte, Trocknungen und Dokumente werden ebenfalls gelöscht.</p>
   </div>
   {userRole==="admin"&&<DeleteCaseButton id={id}/>}
 </section>
 </>}

 {tab==="damage"&&<section className="section grid cols2"><div className="card"><h3>Schadensursache</h3><p>{data.damage_cause||"Noch nicht erfasst."}</p></div><div className="card"><h3>Schadensbeschreibung</h3><p>{data.damage_description||"Noch nicht erfasst."}</p></div><div className="card"><h3>Handlungsempfehlung</h3><p>{data.recommended_action||"Noch nicht erfasst."}</p></div></section>}

 {tab==="photos"&&<section className="section grid cols2"><form id="photoForm" className="card" onSubmit={e=>{e.preventDefault();post("photos",e.currentTarget,photoTransform)}}><h2>Foto aufnehmen / hochladen</h2><div className="field"><label>Foto aufnehmen oder vorhandenes Bild auswählen</label><input id="photoFile" type="file" accept="image/*" required/></div>{userRole==="admin"&&<button type="button" className="button secondary" style={{marginTop:10}} disabled={aiPhoto} onClick={describePhoto}>{aiPhoto?"KI analysiert …":"KI: Bild beschreiben"}</button>}<div className="formGrid" style={{marginTop:12}}><div className="field"><label>Kategorie</label><select name="category"><option value="schadensbild">Schadensbild</option><option value="messbild">Messbild</option><option value="objektbild">Objektbild</option><option value="bauteiloeffnung">Bauteilöffnung</option></select></div><SelectOrCustom name="room" items={STANDARD_ROOMS} label="Raum" placeholder="anderen Raum eingeben"/><div className="field"><label>Bauteil</label><input name="component"/></div><div className="field full"><label>Beschreibung</label><textarea name="caption"/></div></div><button className="button success" style={{marginTop:12}}>Foto speichern</button></form><div className="card"><h2>Bilder</h2><div className="photoGrid">{photos.map(p=><div className="photoCard" key={p.id}><img src={p.file_url} alt={p.caption||"Foto"}/><div className="photoBody"><strong>{p.category}</strong><br/>{p.room||""} {p.component||""}<br/><span className="small">{p.caption||""}</span></div></div>)}</div>{photos.length===0&&<div className="empty">Noch keine Bilder.</div>}</div></section>}

 {tab==="measurements"&&<section className="section grid cols2"><form className="card" onSubmit={e=>{e.preventDefault();post("measurements",e.currentTarget)}}><h2>Messung erfassen</h2><div className="formGrid"><SelectOrCustom name="room" items={STANDARD_ROOMS} label="Raum" placeholder="anderen Raum eingeben"/><SelectOrCustom name="floor" items={STANDARD_FLOORS} label="Etage / Geschoss" placeholder="z. B. 7. OG"/><div className="field"><label>Bauteil</label><select name="component"><option>Wand</option><option>Boden</option><option>Decke</option><option>Estrich</option><option>Holz</option></select></div><div className="field"><label>Messverfahren</label><select name="method"><option>Kapazitives Messverfahren</option><option>Widerstandsmessung</option><option>CM-Messung</option><option>Thermografie</option><option>Sonstiges</option></select></div><div className="field"><label>Messgerät</label><input name="device" placeholder="z. B. Trotec T660"/></div><div className="field"><label>Messwert</label><input name="value_numeric" inputMode="decimal"/></div><div className="field"><label>Einheit</label><input name="unit" defaultValue="digits"/></div><div className="field"><label>Bewertung</label><select name="assessment"><option value="">–</option><option>trocken</option><option>halb feucht</option><option>feucht</option><option>sehr feucht</option><option>nass</option></select></div><div className="field full"><label>Anmerkung</label><textarea name="notes"/></div></div><button className="button success" style={{marginTop:12}}>Messung speichern</button></form><div className="card"><h2>Messverlauf</h2><div className="tableWrap"><table className="simpleTable"><thead><tr><th>Raum</th><th>Bauteil</th><th>Wert</th><th>Bewertung</th></tr></thead><tbody>{measurements.map(m=><tr key={m.id}><td>{m.room||"–"}<br/><span className="muted">{m.floor||""}</span></td><td>{m.component||"–"}</td><td>{m.value_numeric??"–"} {m.unit||""}<br/><span className="muted">{m.device||""}</span></td><td>{m.assessment||m.notes||"–"}</td></tr>)}</tbody></table></div>{measurements.length===0&&<div className="empty">Noch keine Messungen.</div>}</div></section>}

 {tab==="drying"&&<section className="section grid cols2"><form className="card" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form),equipment_ids=fd.getAll("equipment_ids");post("drying",form,o=>({...o,company_id:data.company_id,equipment_ids}))}}><h2>Trocknung anlegen</h2><div className="formGrid"><div className="field"><label>Trocknungsbereich</label><select value={dryingCategory} onChange={e=>setDryingCategory(e.target.value)}><option value="technical">Technische Trocknung</option><option value="insulation">Dämmschichttrocknung</option></select></div><SelectOrCustom name="room" items={STANDARD_ROOMS} label="Raum" placeholder="anderen Raum eingeben"/><SelectOrCustom name="floor" items={STANDARD_FLOORS} label="Etage / Geschoss" placeholder="z. B. 7. OG"/><div className="field"><label>Verfahren</label><select name="drying_method"><option>Kondenstrocknung</option><option>Adsorptionstrocknung</option><option>Dämmschichttrocknung Unterdruck</option><option>Dämmschichttrocknung Überdruck</option><option>Hohlraumtrocknung</option></select></div><div className="field"><label>Aufstellung</label><input type="datetime-local" name="installed_at"/></div><div className="field"><label>Abbau</label><input type="datetime-local" name="removed_at"/></div><div className="field full"><label>Geräte auswählen</label><div className="equipmentList">{filteredEquipment.length===0?<div className="muted small">Für diesen Bereich sind noch keine Geräte angelegt.</div>:filteredEquipment.map(eq=><label className="checkRow" key={eq.id}><input type="checkbox" name="equipment_ids" value={eq.id}/><span><strong>{eq.equipment_code} · {eq.name}</strong>{eq.serial_number?<><br/><span className="muted small">Seriennr. {eq.serial_number}</span></>:null}</span></label>)}</div></div><div className="field full"><label>Hinweise</label><textarea name="notes"/></div></div><button className="button success" style={{marginTop:12}}>Trocknung speichern</button></form><div className="card"><h2>Trocknungsgeräte im Schaden</h2>{drying.map(d=><div key={d.id}><strong>{d.equipment_name?`${d.equipment_code} · ${d.equipment_name}`:(d.room||"Trocknung")}</strong><div className="caseMeta">{d.room||"–"} · {d.drying_method||"–"}<br/>{new Date(d.installed_at).toLocaleString("de-DE")} {d.removed_at?"bis "+new Date(d.removed_at).toLocaleString("de-DE"):"· aktiv"}<br/>{d.notes||""}</div><div className="divider"/></div>)}{drying.length===0&&<div className="empty">Noch keine Trocknung erfasst.</div>}</div></section>}

 {tab==="reports"&&<section className="section grid cols2"><form className="card" onSubmit={e=>{e.preventDefault();post("work-reports",e.currentTarget,o=>({...o,company_id:data.company_id}))}}><h2>Digitalen Rapport anlegen</h2><div className="formGrid"><div className="field"><label>Datum</label><input type="date" name="report_date"/></div><div className="field"><label>Mitarbeiter</label><input name="worker_name"/></div><div className="field"><label>Funktion</label><input name="function" defaultValue="Techniker"/></div><div className="field"><label>Rapport-Nr.</label><input name="report_number"/></div><div className="field"><label>Arbeitsbeginn</label><input type="time" name="work_start"/></div><div className="field"><label>Arbeitsende</label><input type="time" name="work_end"/></div><div className="field"><label>Pause Minuten</label><input type="number" name="break_minutes" defaultValue="0"/></div><div className="field"><label>An-/Abfahrten</label><input type="number" name="trips_count" defaultValue="1"/></div><div className="field full"><label>Leistungsbeschreibung</label><textarea name="description"/></div></div><button className="button success" style={{marginTop:12}}>Rapport speichern</button></form><div className="card"><h2>Rapporte</h2>{reports.map(r=><div key={r.id}><strong>{new Date(r.report_date).toLocaleDateString("de-DE")} · {r.worker_name||"Mitarbeiter"}</strong><div className="caseMeta">{r.work_start||"–"} – {r.work_end||"–"} · Fahrten: {r.trips_count}<br/>{r.description||""}</div><div className="divider"/></div>)}{reports.length===0&&<div className="empty">Noch keine Rapporte.</div>}</div></section>}

 {tab==="energy"&&<section className="section grid cols2"><form className="card" onSubmit={e=>{e.preventDefault();post("energy",e.currentTarget)}}><h2>Stromverbrauch erfassen</h2><div className="formGrid"><div className="field full"><label>Wohneinheit / Bereich</label><input name="unit_name"/></div><div className="field"><label>Beginn</label><input type="date" name="start_date"/></div><div className="field"><label>Ende</label><input type="date" name="end_date"/></div><div className="field"><label>Anfangszählerstand</label><input name="meter_start" inputMode="decimal"/></div><div className="field"><label>Endzählerstand</label><input name="meter_end" inputMode="decimal"/></div><div className="field"><label>Verbrauch kWh</label><input name="consumption_kwh" inputMode="decimal"/></div><div className="field"><label>Strompreis €/kWh</label><input name="price_per_kwh" inputMode="decimal"/></div></div><button className="button success" style={{marginTop:12}}>Speichern</button></form><div className="card"><h2>Bisherige Einträge</h2>{energy.map(e=>{const cost=e.consumption_kwh!=null&&e.price_per_kwh!=null?e.consumption_kwh*e.price_per_kwh:null;return <div key={e.id}><div className="caseTitle">{e.unit_name||"Bereich"}</div><div className="caseMeta">{e.start_date||"–"} bis {e.end_date||"–"}<br/>Verbrauch: <strong>{e.consumption_kwh??"–"} kWh</strong>{cost!=null?<> · Kosten <strong>{cost.toFixed(2)} €</strong></>:null}</div><div className="divider"/></div>})}{energy.length===0&&<div className="empty">Noch kein Stromverbrauch.</div>}</div></section>}

 {tab==="documents"&&<section className="section grid"><DamageReportEditor caseId={id}/><AssignmentEditor caseId={id}/><div className="card"><h2>Dokumente aus diesem Schaden</h2><div className="actions"><Link className="button" href={`/cases/${id}/report`}>Schadensbericht öffnen</Link><Link className="button secondary" href={`/documents/new?case_id=${id}`}>Angebot / Rechnung erstellen</Link></div><p className="muted small">Angebot und Rechnung greifen auf denselben zentralen Artikelkatalog zu. Übernommene Positionen können im Dokument individuell verändert werden, ohne den Katalog zu ändern.</p></div></section>}
 </>}
async function compressImage(file:File,max:number,quality:number){return new Promise<string>((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{let w=img.width,h=img.height;if(w>max){h=Math.round(h*max/w);w=max}if(h>max){w=Math.round(w*max/h);h=max}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d");if(!ctx)return reject(new Error("Bild konnte nicht verarbeitet werden."));ctx.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c.toDataURL("image/jpeg",quality))};img.onerror=()=>reject(new Error("Bild konnte nicht gelesen werden."));img.src=url})}
