"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";import Link from "next/link";
type Article={catalog:string;article_number:string;name:string;description:string;unit:string;unit_price:number|null;source:string;note?:string};type Item={description:string;quantity:number;unit:string;unit_price:number;vat_rate:number;category?:string;source_type?:string};
export default function DocumentBuilder({caseId="",documentId=""}:{caseId?:string;documentId?:string}){
 const[caseData,setCaseData]=useState<any>(null),[doc,setDoc]=useState<any>(null),[items,setItems]=useState<Item[]>([]),[q,setQ]=useState(""),[catalog,setCatalog]=useState("own"),[results,setResults]=useState<Article[]>([]),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[aiText,setAiText]=useState("");
 useEffect(()=>{(async()=>{try{if(documentId){const r=await fetch(`/api/documents/${documentId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setDoc(d);setCaseData(d);setItems((d.items||[]).map((x:any)=>({description:x.description,quantity:Number(x.quantity),unit:x.unit||"",unit_price:Number(x.unit_price),vat_rate:Number(x.vat_rate),category:x.category||"",source_type:x.source_type||"catalog"})))}else if(caseId){const r=await fetch(`/api/cases/${caseId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setCaseData(d)}}catch(e){setErr(e instanceof Error?e.message:"Fehler")}})()},[caseId,documentId]);
 useEffect(()=>{const t=setTimeout(async()=>{if(!q.trim()){setResults([]);return}const r=await fetch(`/api/articles?q=${encodeURIComponent(q)}&catalog=${catalog}&limit=30`);if(r.ok)setResults(await r.json())},250);return()=>clearTimeout(t)},[q,catalog]);
 const net=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0),0),[items]),vat=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0)*((Number(x.vat_rate)||0)/100),0),[items]);
 function addArticle(a:Article){setItems(v=>[...v,{description:`${a.article_number} ${a.name}${a.description&&a.description!==a.name?" – "+a.description:""}`,quantity:1,unit:a.unit||"Stk.",unit_price:Number(a.unit_price||0),vat_rate:19,category:a.source,source_type:a.catalog}])}function addFree(){setItems(v=>[...v,{description:"Freie Position",quantity:1,unit:"Pauschale",unit_price:0,vat_rate:19,source_type:"manual"}])}function patch(i:number,k:keyof Item,v:any){setItems(arr=>arr.map((x,n)=>n===i?{...x,[k]:["quantity","unit_price","vat_rate"].includes(k as string)?Number(v):v}:x))}
 async function fromCase(){if(!(caseId||doc?.case_id))return;const cid=caseId||doc?.case_id,r=await fetch(`/api/cases/${cid}/billing-suggestions`),j=await r.json();if(!r.ok){setErr(j.error||"Vorschläge nicht verfügbar.");return}setQ((j.search_terms||[]).join(" "));setAiText(j.context||"");setMsg("Vorschläge aus Schaden geladen.")}
 async function aiSuggest(){if(!aiText.trim())return;const r=await fetch("/api/ai/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"article_match",context:aiText})}),j=await r.json();if(!r.ok){setErr(j.error||"KI nicht verfügbar.");return}setQ((j.result?.search_terms||[]).join(" ")||aiText)}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body:any=Object.fromEntries(f.entries());body.case_id=caseId||doc?.case_id||null;body.company_id=caseData?.company_id||doc?.company_id;body.items=items;const url=documentId?`/api/documents/${documentId}`:"/api/documents",r=await fetch(url,{method:documentId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setErr(j.error||"Speichern fehlgeschlagen.");return}const id=documentId||j.id;if(id)location.href=`/documents/${id}/view`}
 return <><div className="topbar"><Link className="back" href={caseId?`/cases/${caseId}`:"/"}>← Zurück</Link>{documentId&&<Link className="button secondary" href={`/documents/${documentId}/view`}>Dokumentansicht</Link>}</div><section className="hero"><span className="pill">Dokumenteditor</span><h1>{documentId?"Dokument bearbeiten":"Angebot / Rechnung erstellen"}</h1></section>{err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}
 <section className="grid cols2 section"><div className="card"><h2>Artikel finden</h2>{(caseId||doc?.case_id)&&<button type="button" className="button secondary" onClick={fromCase}>Aus Schaden Artikel vorschlagen</button>}<div className="field"><label>Leistung frei beschreiben (KI)</label><textarea value={aiText} onChange={e=>setAiText(e.target.value)}/></div><button className="button secondary" type="button" onClick={aiSuggest}>KI: passende Suchbegriffe</button><div className="formGrid"><div className="field"><label>Katalog</label><select value={catalog} onChange={e=>setCatalog(e.target.value)}><option value="own">Eigener Katalog Erhard/Dryland</option><option value="axa">AXA-Leistungsverzeichnis</option><option value="all">Alle</option></select></div><div className="field"><label>Artikelsuche</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Schadensbericht, Leckageortung, Trocknung ..."/></div></div><div style={{maxHeight:430,overflow:"auto"}}>{results.map((a,i)=><div key={`${a.catalog}${a.article_number}${i}`} className="checkRow"><div style={{flex:1}}><strong>{a.article_number} · {a.name}</strong><div className="caseMeta">{a.unit} · {Number(a.unit_price||0).toFixed(2)} €<br/>{a.source}</div></div><button className="button secondary" type="button" onClick={()=>addArticle(a)}>Übernehmen</button></div>)}</div><button className="button secondary" type="button" onClick={addFree}>+ freie Position</button></div>
 <form className="card" onSubmit={save}><h2>Dokument</h2><div className="formGrid"><div className="field"><label>Art</label><select name="document_type" defaultValue={doc?.document_type||"angebot"}><option value="angebot">Angebot</option><option value="rechnung">Rechnung</option></select></div><div className="field"><label>Status</label><select name="status" defaultValue={doc?.status||"entwurf"}><option>entwurf</option><option>freigegeben</option><option>versendet</option><option>bezahlt</option><option>storniert</option></select></div><div className="field"><label>Nummer</label><input name="document_number" defaultValue={doc?.document_number||""}/></div><div className="field"><label>Datum</label><input type="date" name="document_date" defaultValue={String(doc?.document_date||new Date().toISOString()).slice(0,10)}/></div><div className="field full"><label>Titel</label><input name="title" defaultValue={doc?.title||caseData?.title||caseData?.case_title||""}/></div></div><div className="divider"/><h3>Positionen</h3>{items.length===0?<div className="empty">Noch keine Positionen.</div>:items.map((x,i)=><div className="card" style={{marginBottom:10,padding:10}} key={i}><div className="field"><label>Beschreibung</label><textarea value={x.description} onChange={e=>patch(i,"description",e.target.value)}/></div><div className="formGrid"><div className="field"><label>Menge</label><input type="number" step="0.01" value={x.quantity} onChange={e=>patch(i,"quantity",e.target.value)}/></div><div className="field"><label>Einheit</label><input value={x.unit} onChange={e=>patch(i,"unit",e.target.value)}/></div><div className="field"><label>Einzelpreis €</label><input type="number" step="0.01" value={x.unit_price} onChange={e=>patch(i,"unit_price",e.target.value)}/></div><div className="field"><label>USt. %</label><input type="number" step="0.01" value={x.vat_rate} onChange={e=>patch(i,"vat_rate",e.target.value)}/></div></div><button type="button" className="button secondary" onClick={()=>setItems(a=>a.filter((_,n)=>n!==i))}>Position löschen</button></div>)}<div className="divider"/><strong>Netto:</strong> {net.toFixed(2)} €<br/><strong>USt.:</strong> {vat.toFixed(2)} €<br/><strong>Gesamt:</strong> {(net+vat).toFixed(2)} €<br/><button className="button success" style={{marginTop:14}}>{documentId?"Speichern & ansehen":"Dokument erstellen & ansehen"}</button></form></section></>
}
