"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {mergeDryingItems,applyCatalogPrice} from "@/lib/document-items";
import OfferPhotoAssistant from "@/components/OfferPhotoAssistant";
type Article={catalog:string;article_number:string;name:string;description:string;unit:string;unit_price:number|null;source:string;note?:string};
type Item={description:string;quantity:number;unit:string;unit_price:number;vat_rate:number;category?:string;source_type?:string};

export default function DocumentBuilder({caseId="",documentId="",initialType="angebot",sourceDocumentId=""}:{caseId?:string;documentId?:string;initialType?:string;sourceDocumentId?:string}){
 const[caseData,setCaseData]=useState<any>(null),[doc,setDoc]=useState<any>(null),[items,setItems]=useState<Item[]>([]),[q,setQ]=useState(""),[catalog,setCatalog]=useState("own"),[results,setResults]=useState<Article[]>([]),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[aiText,setAiText]=useState(""),[suggestions,setSuggestions]=useState<any>(null);
 const[effectiveCaseId,setEffectiveCaseId]=useState(caseId),[loading,setLoading]=useState(true),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState(""),[priceTarget,setPriceTarget]=useState<number|null>(null);
 const[deliveryOverride,setDeliveryOverride]=useState<any>(null),[reverseCharge,setReverseCharge]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{
   let linkedCaseId=caseId;
   if(documentId){const r=await fetch(`/api/documents/${documentId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);linkedCaseId=d.case_id||caseId;setDoc(d);setCaseData(d);setReverseCharge(Boolean(d.reverse_charge));setItems((d.items||[]).map((x:any)=>({description:x.description,quantity:Number(x.quantity),unit:x.unit||"",unit_price:Number(x.unit_price),vat_rate:Number(x.vat_rate),category:x.category||"",source_type:x.source_type||"catalog"})))}
   else if(caseId){const r=await fetch(`/api/cases/${caseId}`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error);setCaseData(d)}
   if(sourceDocumentId&&!documentId){const r=await fetch(`/api/documents/${sourceDocumentId}`,{cache:"no-store"}),s=await r.json();if(!r.ok)throw new Error(s.error||"Angebot konnte nicht geladen werden.");if(r.ok){linkedCaseId=linkedCaseId||s.case_id||"";setCaseData(s);setItems((s.items||[]).map((x:any)=>({description:x.description,quantity:Number(x.quantity),unit:x.unit||"",unit_price:Number(x.unit_price),vat_rate:Number(x.vat_rate),category:x.category||"",source_type:x.source_type||"source_offer"})));setReverseCharge(Boolean(s.reverse_charge));setMsg(`Positionen aus Angebot ${s.document_number||""} übernommen.`)}}
   if(active)setEffectiveCaseId(linkedCaseId);
   if(linkedCaseId){const r=await fetch(`/api/cases/${linkedCaseId}/billing-suggestions`,{cache:"no-store"}),data=await r.json();if(!r.ok)throw new Error(data.error||"Trocknungsdaten konnten nicht geladen werden.");if(active){setSuggestions(data);if(!documentId&&!sourceDocumentId&&initialType==="rechnung")setItems(v=>mergeDryingItems(v,data.suggested_items||[]))}}
 }catch(e){if(active)setErr(e instanceof Error?e.message:"Fehler")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[caseId,documentId,sourceDocumentId,initialType]);

 useEffect(()=>{const controller=new AbortController();setSearching(true);setSearchError("");setResults([]);const t=setTimeout(async()=>{try{const r=await fetch(`/api/articles?q=${encodeURIComponent(q)}&catalog=${catalog}&limit=100`,{signal:controller.signal});const data=await r.json();if(!r.ok)throw new Error(data.error||"Artikelsuche fehlgeschlagen.");if(!controller.signal.aborted)setResults(data)}catch(e){if(!controller.signal.aborted)setSearchError(e instanceof Error?e.message:"Artikelsuche fehlgeschlagen.")}finally{if(!controller.signal.aborted)setSearching(false)}},220);return()=>{clearTimeout(t);controller.abort()}},[q,catalog]);
 const net=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0),0),[items]);
 const vatRaw=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_price)||0)*((Number(x.vat_rate)||0)/100),0),[items]);
 const vat=reverseCharge?0:vatRaw;

 function addArticle(a:Article){setErr("");if(priceTarget!==null){try{const updated=applyCatalogPrice(items[priceTarget],a);setItems(v=>v.map((x,i)=>i===priceTarget?updated:x));setPriceTarget(null);setMsg("Katalogpreis übernommen. Gerätebeschreibung und Laufzeit bleiben erhalten.")}catch(e){setErr(e instanceof Error?e.message:"Preis konnte nicht übernommen werden.")}return}setMsg("Artikel als bearbeitbare Position übernommen.");setItems(v=>[...v,{description:`${a.article_number} ${a.name}${a.description&&a.description!==a.name?" – "+a.description:""}`,quantity:1,unit:a.unit||"Stk.",unit_price:Number(a.unit_price||0),vat_rate:19,category:(a.name.toLowerCase().includes("trocknung")?"Trocknung/Geräteeinsatz":a.name.toLowerCase().includes("an/abfahrt")?"Fahrzeugkostenanteil":a.name.toLowerCase().includes("rapport")||a.name.toLowerCase().includes("stundenbasis")?"Rapportarbeiten":""),source_type:a.catalog}])}
 function addFree(){setItems(v=>[...v,{description:"Freie Position",quantity:1,unit:"Pauschale",unit_price:0,vat_rate:19,category:"Sonstige Leistungen",source_type:"manual"}])}
 function patch(i:number,k:keyof Item,v:any){setItems(arr=>arr.map((x,n)=>n===i?{...x,[k]:["quantity","unit_price","vat_rate"].includes(k as string)?Number(v):v}:x))}
 async function fromCase(){if(!effectiveCaseId)return;setErr("");try{const r=await fetch(`/api/cases/${effectiveCaseId}/billing-suggestions`,{cache:"no-store"}),data=await r.json();if(!r.ok)throw new Error(data.error||"Trocknungsdaten konnten nicht geladen werden.");setSuggestions(data);setQ((data.search_terms||[]).find((x:string)=>/trocknung/i.test(x))||"");setAiText(data.context||"");setMsg("Schadendaten aktualisiert. Trocknungspositionen können übernommen werden.")}catch(e){setErr(e instanceof Error?e.message:"Fehler")}}
 function addDryingSuggestions(){const xs=suggestions?.suggested_items||[];if(!xs.length){setErr("Im Schaden sind noch keine Trocknungsgeräte hinterlegt.");return}setErr("");setItems(v=>mergeDryingItems(v,xs));setMsg("Fehlende Trocknungspositionen übernommen, bereits verknüpfte Positionen nicht verdoppelt. Preise bitte prüfen.")}
 function applyActualDrying(){const xs=suggestions?.suggested_items||[];if(!xs.length)return;setErr("");setItems(v=>mergeDryingItems(v,xs,true));setMsg("Verknüpfte tagesbasierte Laufzeiten aktualisiert; individuelle Preise und Pauschalen bleiben erhalten. Ältere, unverknüpfte Angebotspositionen bitte auf Doppelberechnung prüfen.")}
 async function aiSuggest(){if(!aiText.trim())return;const r=await fetch("/api/ai/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"article_match",context:aiText})}),j=await r.json();if(!r.ok){setErr(j.error||"KI nicht verfügbar.");return}setQ((j.result?.search_terms||[]).join(" ")||aiText)}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setErr("");const f=new FormData(e.currentTarget),body:any=Object.fromEntries(f.entries());body.reverse_charge=reverseCharge;body.case_id=effectiveCaseId||null;body.company_id=caseData?.company_id||doc?.company_id;body.items=items;const url=documentId?`/api/documents/${documentId}`:"/api/documents",r=await fetch(url,{method:documentId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setErr(j.error||"Speichern fehlgeschlagen.");return}const id=documentId||j.id;if(id)location.href=`/documents/${id}/view`}

 const customerName=doc?.customer_company_name||[doc?.first_name,doc?.last_name].filter(Boolean).join(" ")||caseData?.customer_name||"";
 const deliveryName=deliveryOverride?.name||doc?.delivery_name||caseData?.title||customerName||"",deliveryStreet=deliveryOverride?.street||doc?.delivery_street||caseData?.object_street||doc?.object_street||"",deliveryPostal=deliveryOverride?.postal_code||doc?.delivery_postal_code||caseData?.object_postal_code||doc?.object_postal_code||"",deliveryCity=deliveryOverride?.city||doc?.delivery_city||caseData?.object_city||doc?.object_city||"";
 const type=doc?.document_type||initialType;

 return <>
  <div className="topbar"><Link className="back" href={caseId?`/cases/${caseId}`:"/"}>← Zurück</Link>{documentId&&<Link className="button secondary" href={`/documents/${documentId}/view`}>Dokumentansicht</Link>}</div>
  <section className="hero"><span className="pill">Dokumenteditor</span><h1>{documentId?"Dokument bearbeiten":type==="rechnung"?"Rechnung erstellen":"Angebot erstellen"}</h1>{sourceDocumentId&&<p className="muted">Grundlage: vorhandenes Angebot. Für die Rechnung können tatsächliche Trocknungslaufzeiten übernommen werden.</p>}</section>
  {err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}
  {type==="angebot"&&<OfferPhotoAssistant onApply={(xs)=>{setItems(v=>[...v,...xs]);setMsg(`${xs.length} KI-erfasste Position(en) übernommen. Bitte Preise und Mengen prüfen.`)}} onSearch={(terms)=>setQ(terms)} onDelivery={(d)=>setDeliveryOverride(d)}/>}
  <section className="grid cols2 section">
   <div className="card"><h2>Leistungen aus Schaden</h2>{effectiveCaseId&&<div className="actions"><button type="button" className="button secondary" onClick={fromCase}>Schaden auswerten</button>{suggestions?.suggested_items?.length>0&&<button type="button" className="button secondary" onClick={addDryingSuggestions}>Trocknungspositionen übernehmen</button>}{type==="rechnung"&&suggestions?.suggested_items?.length>0&&<button type="button" className="button" onClick={applyActualDrying}>Tatsächliche Trocknung anwenden</button>}</div>}
    {suggestions?.suggested_items?.length>0&&<div className="notice" style={{marginTop:10}}>Erkannt: {suggestions.suggested_items.length} Trocknungsgerät(e), Laufzeiten bei laufenden Geräten vorläufig bis heute; berechneter Verbrauch ca. {Number(suggestions.total_consumption_kwh||0).toLocaleString("de-DE",{maximumFractionDigits:1})} kWh.</div>}
    <div className="divider"/><h2>Artikel finden</h2><div className="field"><label>Leistung frei beschreiben (KI)</label><textarea value={aiText} onChange={e=>setAiText(e.target.value)}/></div><button className="button secondary" type="button" onClick={aiSuggest}>KI: passende Suchbegriffe</button>
    <div className="formGrid" style={{marginTop:9}}><div className="field"><label>Katalog</label><select value={catalog} onChange={e=>setCatalog(e.target.value)}><option value="own">Eigener Katalog</option><option value="axa">AXA</option><option value="all">Alle</option></select></div><div className="field"><label>Artikelsuche</label><input id="article-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="z. B. Technische Trocknung"/></div></div>
    {priceTarget!==null&&<div className="notice">Preis für Position {priceTarget+1} auswählen (gleiche Einheit). <button type="button" onClick={()=>setPriceTarget(null)}>Abbrechen</button></div>}
    {searching&&<p role="status">Artikel werden gesucht …</p>}{searchError&&<div role="alert" className="error">{searchError}</div>}{!searching&&!searchError&&results.length===0&&<p>Keine Artikel gefunden. Suchbegriff kürzen oder „Alle“ wählen.</p>}
    <div style={{maxHeight:360,overflow:"auto"}}>{results.map((a,i)=><div key={`${a.catalog}${a.article_number}${i}`} className="checkRow"><div style={{flex:1}}><strong>{a.article_number} · {a.name}</strong><div className="caseMeta">{a.unit} · {a.unit_price==null?"Preis offen":Number(a.unit_price).toFixed(2)+" €"}<br/>{a.source}</div></div><button className="button secondary smallButton" type="button" onClick={()=>addArticle(a)}>{priceTarget!==null?"Preis zuordnen":"Übernehmen"}</button></div>)}</div><button className="button secondary" type="button" onClick={addFree}>+ freie Position</button>
   </div>

   <form key={doc?.id||"new"} className="card" onSubmit={save}><fieldset disabled={loading} style={{border:0,padding:0,minWidth:0}}><h2>Dokument</h2>{loading&&<p role="status">Dokument und Trocknungsdaten werden geladen …</p>}{items.some(x=>x.unit_price===0)&&<div className="notice">Mindestens eine Position hat 0 € Einzelpreis. Bitte vor Rechnungsabschluss prüfen.</div>}
    <div className="formGrid"><div className="field"><label>Art</label><select name="document_type" defaultValue={type}><option value="angebot">Angebot</option><option value="rechnung">Rechnung</option></select></div><div className="field"><label>Status</label><select name="status" defaultValue={doc?.status||"entwurf"}><option>entwurf</option><option>freigegeben</option><option>versendet</option><option>bezahlt</option><option>storniert</option></select></div><div className="field"><label>Nummer</label><input name="document_number" defaultValue={doc?.document_number||""} placeholder={documentId?"":"wird automatisch vergeben"}/><small>{documentId?"Bestehende Nummer":"Leer lassen = fortlaufende Nummer aus Firmendaten"}</small></div><div className="field"><label>Datum</label><input type="date" name="document_date" defaultValue={String(doc?.document_date||new Date().toISOString()).slice(0,10)}/></div><div className="field full"><label>Titel / Betreff</label><input name="title" defaultValue={doc?.title||caseData?.title||caseData?.case_title||""}/></div></div>
    <div className="divider"/><h3>Steuer</h3><label className="checkRow"><input type="checkbox" name="reverse_charge" checked={reverseCharge} onChange={e=>setReverseCharge(e.target.checked)}/><span><strong>§13b / Steuerschuldnerschaft des Leistungsempfängers</strong><br/><span className="muted small">Bei Aktivierung wird keine Umsatzsteuer berechnet und der gesetzliche Hinweis im Dokument ausgegeben.</span></span></label>
    <div className="divider"/><h3>Leistungszeitraum</h3><div className="formGrid"><div className="field"><label>von</label><input type="date" name="service_period_from" defaultValue={String(doc?.service_period_from||"").slice(0,10)}/></div><div className="field"><label>bis</label><input type="date" name="service_period_to" defaultValue={String(doc?.service_period_to||"").slice(0,10)}/></div></div>
    <div className="divider"/><h3>Liefer-/Leistungsadresse</h3><div className="formGrid"><div className="field full"><label>Name / Objekt</label><input key={`dn-${deliveryName}`} name="delivery_name" defaultValue={deliveryName}/></div><div className="field full"><label>Straße / Hausnummer</label><input key={`ds-${deliveryStreet}`} name="delivery_street" defaultValue={deliveryStreet}/></div><div className="field"><label>PLZ</label><input key={`dp-${deliveryPostal}`} name="delivery_postal_code" defaultValue={deliveryPostal}/></div><div className="field"><label>Ort</label><input key={`dc-${deliveryCity}`} name="delivery_city" defaultValue={deliveryCity}/></div></div>
    <div className="divider"/><h3>Positionen</h3>{items.length===0?<div className="empty">Noch keine Positionen.</div>:items.map((x,i)=><div className="card" style={{marginBottom:8,padding:9}} key={i}><div className="field"><label>Gruppe / Überschrift</label><input value={x.category||""} onChange={e=>patch(i,"category",e.target.value)} placeholder="z. B. Trocknung/Geräteeinsatz"/></div><div className="field"><label>Beschreibung</label><textarea value={x.description} onChange={e=>patch(i,"description",e.target.value)}/></div><div className="formGrid"><div className="field"><label>Menge</label><input type="number" step="0.01" value={x.quantity} onChange={e=>patch(i,"quantity",e.target.value)}/></div><div className="field"><label>Einheit</label><input value={x.unit} onChange={e=>patch(i,"unit",e.target.value)}/></div><div className="field"><label>Einzelpreis €</label><input type="number" step="0.01" value={x.unit_price} onChange={e=>patch(i,"unit_price",e.target.value)}/></div><div className="field"><label>USt. %</label><input type="number" step="0.01" value={x.vat_rate} onChange={e=>patch(i,"vat_rate",e.target.value)} disabled={reverseCharge}/></div></div><button type="button" className="button secondary smallButton" onClick={()=>{setPriceTarget(null);setItems(a=>a.filter((_,n)=>n!==i))}}>Position löschen</button> <button type="button" className="button secondary smallButton" onClick={()=>{setPriceTarget(i);setQ(/drying/.test(x.source_type||"")?"Trocknung":x.description);document.getElementById("article-search")?.scrollIntoView({behavior:"smooth"})}}>Preis aus Artikelverzeichnis</button></div>)}
    <div className="divider"/><div style={{textAlign:"right"}}><strong>Netto:</strong> {net.toFixed(2)} €<br/><strong>USt.:</strong> {vat.toFixed(2)} €{reverseCharge&&<span className="muted"> (§13b)</span>}<br/><strong>Gesamt:</strong> {(net+vat).toFixed(2)} €</div><button className="button success" style={{marginTop:12}}>{documentId?"Speichern & ansehen":"Dokument erstellen & ansehen"}</button>
   </fieldset></form>
  </section>
 </>
}
