"use client";
import {FormEvent,useEffect,useState} from "react";
type Company={id:string;code:string;name:string};
type Eq={id:string;company_id:string;equipment_code:string;name:string;equipment_type:string|null;serial_number:string|null;power_watts:number|null;company_name:string};
async function imageToData(file:File,max=1400){return await new Promise<string>((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{let w=img.width,h=img.height;if(w>max){h=Math.round(h*max/w);w=max}if(h>max){w=Math.round(w*max/h);h=max}const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d");if(!x)return reject(new Error("Bildfehler"));x.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c.toDataURL("image/jpeg",.76))};img.onerror=()=>reject(new Error("Bild konnte nicht gelesen werden."));img.src=url})}
export default function EquipmentManager(){
 const[companies,setCompanies]=useState<Company[]>([]),[items,setItems]=useState<Eq[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[ai,setAi]=useState(false);
 async function load(){try{const[a,b]=await Promise.all([fetch("/api/companies",{cache:"no-store"}),fetch("/api/equipment",{cache:"no-store"})]);setCompanies(await a.json());setItems(await b.json())}catch{setError("Daten konnten nicht geladen werden.")}}
 useEffect(()=>{load()},[]);
 async function recognize(){setError("");setMessage("");const input=document.querySelector<HTMLInputElement>("#equipmentPhoto"),file=input?.files?.[0];if(!file){setError("Bitte zuerst Gerät oder Typenschild fotografieren.");return}setAi(true);try{const image=await imageToData(file);const r=await fetch("/api/ai/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:"equipment",image})});const j=await r.json();if(!r.ok)throw new Error(j.error||"KI nicht verfügbar.");const d=j.result||{};const form=document.querySelector<HTMLFormElement>("#equipmentForm");if(!form)return;const set=(n:string,v:any)=>{const el=form.elements.namedItem(n) as HTMLInputElement|HTMLSelectElement|null;if(el&&v!==null&&v!==undefined&&String(v)!=="")el.value=String(v)};set("name",[d.manufacturer,d.model].filter(Boolean).join(" ")||d.name);set("serial_number",d.serial_number);set("power_watts",d.power_watts);set("equipment_type",d.equipment_type);set("equipment_code",d.equipment_code_suggestion);setMessage("KI-Vorschlag eingetragen. Bitte Werte prüfen und anschließend speichern.")}catch(e){setError(e instanceof Error?e.message:"KI-Analyse fehlgeschlagen.")}finally{setAi(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setMessage("");const form=e.currentTarget,res=await fetch("/api/equipment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))});const j=await res.json();if(!res.ok){setError(j.error||"Fehler");return}form.reset();setMessage("Gerät wurde angelegt.");await load()}
 const label=(t:string|null)=>t==="technical"?"Technische Trocknung":t==="insulation"?"Dämmschichttrocknung":t==="universal"?"Beide Bereiche":"Sonstige";
 return <section className="grid cols2"><form id="equipmentForm" className="card" onSubmit={submit}><h2>Gerät anlegen</h2>{error&&<div className="error">{error}</div>}{message&&<div className="notice">{message}</div>}
 <div className="field" style={{marginTop:12}}><label>Gerät / Typenschild fotografieren</label><input id="equipmentPhoto" type="file" accept="image/*" capture="environment"/></div><button type="button" className="button secondary" onClick={recognize} disabled={ai}>{ai?"KI analysiert …":"KI: Gerät erkennen & Formular ausfüllen"}</button>
 <div className="formGrid" style={{marginTop:12}}><div className="field"><label>Firma *</label><select name="company_id" required defaultValue=""><option value="" disabled>Firma auswählen</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>Gerätenummer *</label><input name="equipment_code" required placeholder="z. B. TTK-01"/></div><div className="field full"><label>Bezeichnung *</label><input name="name" required/></div><div className="field"><label>Kategorie</label><select name="equipment_type" defaultValue="technical"><option value="technical">Technische Trocknung</option><option value="insulation">Dämmschichttrocknung</option><option value="universal">Beide Bereiche</option></select></div><div className="field"><label>Seriennummer</label><input name="serial_number"/></div><div className="field"><label>Leistung Watt</label><input name="power_watts" inputMode="decimal"/></div></div><button className="button success" style={{marginTop:14}}>Gerät speichern</button></form>
 <div className="card"><h2>Vorhandene Geräte</h2>{items.length===0?<div className="empty">Noch keine Geräte angelegt.</div>:items.map(x=><div key={x.id}><strong>{x.equipment_code} · {x.name}</strong><div className="caseMeta">{x.company_name} · {label(x.equipment_type)}{x.serial_number?<><br/>Seriennr.: {x.serial_number}</>:null}{x.power_watts?<><br/>{x.power_watts} W</>:null}</div><div className="divider"/></div>)}</div></section>
}
