"use client";
import {FormEvent,useEffect,useState} from "react";import QRCode from "qrcode";
export default function EquipmentUnitDetail({token}:{token:string}){
 const[data,setData]=useState<any>(null),[qr,setQr]=useState(""),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 async function load(){const r=await fetch(`/api/equipment/unit/${token}`,{cache:"no-store"});const j=await r.json();if(!r.ok){setErr(j.error||"Fehler");return}setData(j);setQr(await QRCode.toDataURL(window.location.href,{width:260,margin:1}))}
 useEffect(()=>{load()},[token]);
 async function maintenance(e:FormEvent<HTMLFormElement>){e.preventDefault();setErr("");const f=e.currentTarget,r=await fetch(`/api/equipment/unit/${token}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(f).entries()))}),j=await r.json();if(!r.ok){setErr(j.error||"Fehler");return}f.reset();setMsg("Wartung gespeichert.");await load()}
 async function settings(e:FormEvent<HTMLFormElement>){e.preventDefault();const r=await fetch(`/api/equipment/unit/${token}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))}),j=await r.json();if(!r.ok){setErr(j.error||"Fehler");return}setMsg("Gerätedaten gespeichert.");await load()}
 if(!data)return <div className="card">{err||"Lade Gerät …"}</div>;
 return <><section className="grid cols2"><div className="card"><h2>{data.unit_code}</h2><h3>{data.equipment_code} · {data.equipment_name}</h3>{qr&&<img src={qr} alt="QR-Code" style={{maxWidth:260,width:"100%"}}/>}<p className="caseMeta">Seriennummer: {data.serial_number||"–"}<br/>Leistung: {data.power_watts?`${data.power_watts} W`:"–"}<br/>Wartungsintervall: {data.maintenance_interval_months} Monate</p><button className="button secondary" onClick={()=>window.print()}>QR / Geräteseite drucken</button></div>
  <form className="card" onSubmit={settings}><h2>Gerätedaten</h2><div className="field"><label>Seriennummer</label><input name="serial_number" defaultValue={data.serial_number||""}/></div><div className="field"><label>Inbetriebnahme</label><input type="date" name="commissioned_at" defaultValue={String(data.commissioned_at||"").slice(0,10)}/></div><div className="field"><label>Wartungsintervall (Monate)</label><input type="number" min="1" name="maintenance_interval_months" defaultValue={data.maintenance_interval_months||12}/></div><button className="button success">Gerätedaten speichern</button></form>
 </section>
 {msg&&<div className="notice">{msg}</div>}{err&&<div className="error">{err}</div>}
 <section className="grid cols2 section"><form className="card" onSubmit={maintenance}><h2>Wartung eintragen</h2><div className="field"><label>Datum</label><input type="date" name="maintenance_date" defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="field"><label>Art der Wartung</label><input name="maintenance_type" placeholder="z. B. Filterreinigung / Elektroprüfung"/></div><div className="field"><label>Durchgeführt von</label><input name="performed_by"/></div><div className="field"><label>Nächste Wartung (optional)</label><input type="date" name="next_due_date"/></div><div className="field"><label>Kosten € (optional)</label><input type="number" step="0.01" name="cost"/></div><div className="field"><label>Bemerkungen</label><textarea name="notes"/></div><button className="button success">Wartung speichern</button></form>
  <div className="card"><h2>Wartungshistorie</h2>{data.maintenance?.length?data.maintenance.map((m:any)=><div key={m.id} className="editableRow"><div><strong>{new Date(m.maintenance_date).toLocaleDateString("de-DE")} · {m.maintenance_type||"Wartung"}</strong><div className="caseMeta">{m.performed_by||""}{m.notes?<><br/>{m.notes}</>:null}<br/>Nächste Wartung: {m.next_due_date?new Date(m.next_due_date).toLocaleDateString("de-DE"):"–"}</div></div></div>):<div className="empty">Noch keine Wartung eingetragen.</div>}</div>
 </section></>
}
