"use client";import {FormEvent,useEffect,useState} from "react";import {useRouter,useSearchParams} from "next/navigation";import Link from "next/link";
export default function LoginForm(){const[err,setErr]=useState(""),[setup,setSetup]=useState(false),[busy,setBusy]=useState(false),[forgot,setForgot]=useState(false),router=useRouter(),sp=useSearchParams();
 useEffect(()=>{fetch("/api/auth/status",{cache:"no-store"}).then(r=>r.json()).then(j=>setSetup(Boolean(j.setup_required))).catch(()=>{})},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))});const j=await r.json();if(!r.ok){setErr(j.error||"Anmeldung fehlgeschlagen.");setBusy(false);return}router.replace(sp.get("next")||"/");router.refresh()}
 async function requestReset(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr("");const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries()))}),j=await r.json();setErr(j.message||j.error||"Anfrage abgeschlossen.");setBusy(false)}
 if(forgot)return <form className="card authCard" onSubmit={requestReset}><h1>Kennwort vergessen</h1><p className="muted">Wir senden einen zeitlich begrenzten Link an die hinterlegte E-Mail-Adresse.</p>{err&&<div className="error">{err}</div>}<div className="field"><label>E-Mail-Adresse</label><input type="email" name="email" required/></div><button className="button" disabled={busy}>{busy?"Senden …":"Link anfordern"}</button><button type="button" className="button secondary" onClick={()=>{setForgot(false);setErr("")}}>Zur Anmeldung</button></form>;
 return <form className="card authCard" onSubmit={submit}><h1>Anmelden</h1><p className="muted">Erhard & Dryland Schadenmanagement</p>{err&&<div className="error">{err}</div>}
 <div className="field"><label>Benutzername</label><input name="username" autoComplete="username" required/></div><div className="field"><label>Passwort</label><input type="password" name="password" autoComplete="current-password" required/></div>
 <button className="button" disabled={busy}>{busy?"Anmeldung …":"Anmelden"}</button><button type="button" className="button secondary" onClick={()=>{setForgot(true);setErr("")}}>Kennwort vergessen</button>{setup&&<p className="small" style={{marginTop:14}}>Noch kein Benutzer vorhanden. <Link href="/setup">Ersten Admin einrichten</Link></p>}</form>}
